apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kyb6dqc8x-go
  janus-idp.io/tekton: kyb6dqc8x-go
  backstage.io/kubernetes-id: kyb6dqc8x-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kyb6dqc8x-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
