apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kyb6dqc8x-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kyb6dqc8x-go 
  name: kyb6dqc8x-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kyb6dqc8x-go 
